// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_sVZvQ4-ePWV_OzIFXDZpwhEt3iS94M',
    appId: '1:256337442137:web:c424624bc842aa1b884848',
    messagingSenderId: '256337442137',
    projectId: 'swayamraksha-57c9e',
    authDomain: 'swayamraksha-57c9e.firebaseapp.com',
    storageBucket: 'swayamraksha-57c9e.appspot.com',
    measurementId: 'G-K7CYERSNMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYQQuABKIxpdqDJAppc6U2Z_tLmJGn-M',
    appId: '1:256337442137:android:cf30fffbf4ed0f8f884848',
    messagingSenderId: '256337442137',
    projectId: 'swayamraksha-57c9e',
    storageBucket: 'swayamraksha-57c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjh5t6Ksu3RIwPQvgzK196WBo7I34ZgSU',
    appId: '1:256337442137:ios:e9a4b8a681bd23e0884848',
    messagingSenderId: '256337442137',
    projectId: 'swayamraksha-57c9e',
    storageBucket: 'swayamraksha-57c9e.appspot.com',
    iosBundleId: 'com.example.swayamraksha',
  );
}
